#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'        # http://redsymbol.net/articles/unofficial-bash-strict-mode/

gem install octokit

git config --global user.email "bot@precog.com"
git config --global user.name "Precog Bot"
git config github.actor precog-bot
